services:
  fitmi-user:
    image: registry.gitlab.com/fit-projects/fitmi-user-service:76098451
    ports:
      - "8085:8085"
    restart: unless-stopped
  fitmi-activity:
    image: registry.gitlab.com/fit-projects/fitmi-activity-service:e0fb5bbb
    ports:
      - "8086:8086"
    restart: unless-stopped
  fitmi-vue:
    image: registry.gitlab.com/fit-projects/fitmi-vue:86ee6c25
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - fitmi-user
      - fitmi-activity
