services:
  fitmi-user:
    image: registry.gitlab.com/fit-projects/fitmi-user-service:8bec1b38
    ports:
      - "8085:8085"
    restart: unless-stopped
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx320m"
  fitmi-activity:
    image: registry.gitlab.com/fit-projects/fitmi-activity-service:937859b0
    ports:
      - "8086:8086"
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx320m"
  fitmi-vue:
    image: registry.gitlab.com/fit-projects/fitmi-vue:86ee6c25
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - fitmi-user
      - fitmi-activity
