services:
  fitmi-user:
    image: registry.gitlab.com/fit-projects/fitmi-user-service:561dbc51
    ports:
      - "8085:8085"
    restart: unless-stopped
  fitmi-activity:
    image: registry.gitlab.com/fit-projects/fitmi-activity-service:e2771a0b
    ports:
      - "8086:8086"
    restart: unless-stopped
  fitmi-vue:
    image: registry.gitlab.com/fit-projects/fitmi-vue:8c7a8760
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - fitmi-user
      - fitmi-activity
